apiVersion: apps/v1
kind: Deployment
metadata:
  name: terangamath
  labels:
    app: terangamath
spec:
  replicas: 2
  selector:
    matchLabels:
      app: terangamath
  template:
    metadata:
      labels:
        app: terangamath
    spec:
      containers:
        - name: app
          image: terangamath:latest   # Remplacer par ton registry, ex: ghcr.io/org/terangamath:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
      # Pas de volume nécessaire : app 100% statique
