apiVersion: v1
kind: Service
metadata:
  name: terangamath
  namespace: terangamath-prod
  labels:
    app: terangamath
spec:
  selector:
    app: terangamath
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
