apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: terangamath
  namespace: terangamath-prod
  annotations:
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - www.terangamath.org
  rules:
    - host: www.terangamath.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: terangamath
                port:
                  number: 80
